### ISSUE TITLE
Node sent to SubDirective is always ParagraphNode

### ISSUE THREAD

**Issue by nikophil** [doctrine/rst-parser#11]
Hi,

the text provided for any SubDirective is always sent through a `ParagraphNode` 
This is quite annoying, when we want to add some class to the surrounding `<p>`, and even worse when we want to add some other markup - the only way to do it seems a little bit hacky... 

Example :
```rst
.. versionadded:: 4.1
    This option was introduced in Symfony 2.6 and replaces another option, which is available prior to 2.6.
```
Expected html would be:
```html
<div class="versionadded">
    <p>
        <span class="versionmodified">New in version 4.1: </span>
        This option was introduced in Symfony 2.6 and replaces another option, which is available prior to 2.6.
    </p>
</div>
```

All the surrounding div could be handled with a `WrapperNode`, except the `<span>`:
```php
    return new WrapperNode($document, '<div class="versionadded">', '</div>');
```

i would like to have your feedback about that ?

thanks a lot.

**Comment by jwage** [comment]
This is how I have versionadded implemented for the Doctrine website https://github.com/doctrine/doctrine-website/blob/master/lib/RST/Directive/VersionAddedDirective.php

**Comment by nikophil** [comment]
ok that's perfect, thanks!
