### ISSUE TITLE
master branch is 36 commits ahead of 0.2.x

### ISSUE THREAD

**Issue by weaverryan** [doctrine/rst-parser#132]
Hey @greg0ire (I assume you will be the person that knows the answer 😄 )!

We were trying to figure out why a method on `rst-parser` was missing over in - https://github.com/weaverryan/docs-builder/pull/27#discussion_r582176979 - and @nikophil discovered that some commits are only on `master` in this repository - https://github.com/doctrine/rst-parser/tree/master

Do you know how that happened? There are several few commits over there that I had originally made, and that we need. And do you think we can just merge master into 0.2.x?

Thanks!

**Comment by greg0ire** [comment]
Hi! I'm on my phone and AFK until Sunday evening, it's unclear to me if I messed something up when releasing 0.2.0 or it you having an issue right now is coincidental. I've been working on getting rid of master branches on most Doctrine repositories lately, one of the reasons for this was to avoid that kind of confusion. Given the big number of changes there are, maybe this will be a good occasion to rename master to 1.0.x and to release 1.0.0, making the situation of this repository more standard. I'll take a look at this as soon as I'm back!

**Comment by greg0ire** [comment]
I think I confused everyone by releasing 0.2.0 when there were so many features added to master that are still unreleased. I noticed that many of them were added to milestone 1.0.0. IMO the best course of action would be to rename master to 1.0.x and then release 1.0.0. I just merged up 0.2.x into master, so nothing should be missing anywhere after that. Sorry again for the confusion, I had no idea there was that much divergence between both branches in the first place.

**Comment by greg0ire** [comment]
In fact, I notice that 1.0.x already exists (I must be the one who created it). So master can be removed instead of renamed.

**Comment by greg0ire** [comment]
master is now removed. I think I will release 1.0.0 tonight, feel free to voice any objections @weaverryan @wouterj @nikophil

**Comment by wouterj** [comment]
I'm very new to the development process of this package, so forgive me if I talk completely nonsense :)

I started looking at https://github.com/weaverryan/docs-builder/issues/38 / https://github.com/doctrine/rst-parser/pull/86 and to me, it seems like list parsing needs some work to be reStructuredText-compatible (and I guess we're having a bit more complex lists in the Symfony docs than the Doctrine docs).
I'm not sure whether such rewrite is possible according to the backwards compatibility promise of this package (I don't see any `@internal` classes, I guess that's a required step before 1.0.0?).

For weaverryan/docs-builder, we actually don't necessarily need a 1.0 release. As we're trying to make it part of the tool chain of symfony.com, we did want to get rid of the `dev-master` dependency (https://github.com/weaverryan/docs-builder/pull/28). So any tag with these changes included is fine (lots of work is needed on symfony.com, so we probably can manage any non-BC changes from e.g. 0.3 to 0.4).

**Comment by greg0ire** [comment]
I'm very  new to this package as a maintainer too. You seem know more about it than I do already, so I'll just trust you about where we are and create a brand new 0.3.x branch from 1.0.x, and release 0.3.0

**Comment by greg0ire** [comment]
# Todo

- [x] create 0.3.x
- [x] move all PRs since 0.2.0 to that milestone
- [x] release 0.3.0

**Comment by greg0ire** [comment]
Since it's unclear how much work must be done until 1.0.0 is released, I created 0.4.x for new features. They can contain BC-break, that is semver-compatible.

**Comment by wouterj** [comment]
:+1: Thanks for all your prompt work tonight @greg0ire!

My view of this package is: it proved itself on the Doctrine docs[1].. but reStructuredText/Sphinx is a very advanced format. It turns out we're using some feature in Symfony that aren't used by Doctrine. @javiereguiluz is currently doing a great job in reporting anything he finds over in Ryan's repository. I guess we can make a good plan for 1.0 in a few weeks based on whatever we find.

I think it's also good to determine some sort of policy for this package (e.g. do we want classes to become `@internal`, when are changes on specific things allowed (e.g. changing which nodes are generated by the parser, how nodes are rendered, etc).

[1] I also found https://github.com/doctrine/rst-parser/issues/105 , it seems like this also breaks the Doctrine docs: https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/types.html#mapping-matrix
