### ISSUE TITLE
Code blocks part of a list item are not parsed

### ISSUE THREAD

**Issue by fabpot** [doctrine/rst-parser#142]
Consider the following RST snippet:

```rst
* Item 1:

  .. code-block:: php

    <?php echo $var ?>
```

The code block is not parsed and considered as text.

**Comment by greg0ire** [comment]
Hi! I think @wouterj plans to work on this: https://github.com/doctrine/rst-parser/pull/138#issuecomment-799646611

**Comment by wouterj** [comment]
Yes, I'm working on parsing lists just like directives and definitions lists (i.e. parsing the contents as subcontents).

However, lists are currently parsed in a really difficult method, so it takes some rewriting :sweat: (and I didn't have much time this week).

**Comment by wouterj** [comment]
This can be closed as https://github.com/doctrine/rst-parser/pull/143 is merged.

**Comment by fabpot** [comment]
It works great! Thank you.
