### ISSUE TITLE
Encoding in table column is garbled

### ISSUE THREAD

**Issue by lavaux** [doctrine/rst-parser#177]
Multi-line table element is garbled after the first line. I tracked this down to a request to double encode a UTF-8 string with utf8_encode at the line https://github.com/doctrine/rst-parser/blob/9107ba8b1dc8dc2dda2438cd38c609c74d2c33fe/lib/Nodes/Table/TableColumn.php#L57  (TableColumn::addContent). The function is provided with some content that has already been encoded, resulting in garbled data.

Example data:
```RST
+---+-------+
| A | B     | 
+===+=======+
| x | é à \ |  
|   | é     |
+---+-------+
```

This result in
```HTML
<tbody>
  <tr>
      <td>x</td>
       <td>é à<br />Ã©</td>
  </tr>
</tbody>
```
which is obviously incorrect.

**Comment by greg0ire** [comment]
I think this was introduced in https://github.com/doctrine/rst-parser/pull/100 . @weaverryan , do you remember what purpose this serves?

**Comment by lavaux** [comment]
No news from that side ?
