### ISSUE TITLE
Toctrees and Globs with wildcards don't seem to work

### ISSUE THREAD

**Issue by linawolf** [doctrine/rst-parser#183]
In the TYPO3 changelog we frequently work in toctrees with wildcarded globs, i.e.

```
Features
^^^^^^^^

.. toctree::
   :maxdepth: 1
   :titlesonly:
   :glob:

   Feature-*
```

To display all Feature Changelog entries. These work without issue in Sphinx but fail on the doctrine rst-parser

**Comment by greg0ire** [comment]
https://github.com/doctrine/rst-parser/pull/24 seems to add support for that, and there are tests to ensure it still works.


> but fail on the doctrine rst-parser

Do you mean an exception is thrown? What's the end result?

I wanted to ask you to contribute a failing test, but it appears the test suite is currently broken, so I guess I'll focus on that first :sweat_smile:

**Comment by linawolf** [comment]
Once the test suite is fixed, I will be happy to

**Comment by greg0ire** [comment]
I think I found a fix, just not sure it's the right one: https://github.com/doctrine/rst-parser/pull/184

**Comment by linawolf** [comment]
Thank you @greg0ire  attached is a failing test, it failed locally, Someone :tm: would however have to approve that I may run them on GitHub.
