### ISSUE TITLE
toctree ignores titlesonly option

### ISSUE THREAD

**Issue by linawolf** [doctrine/rst-parser#192]
When the option `:titlesonly:` is set the toctree may only contain the main titles of the documents, not the subtitles within. The main title of a document is defined to be the first one, no matter the syntax of underline / upperline

https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree

I will provide a test

**Comment by linawolf** [comment]
@greg0ire it seems like I lack the rights to put this on draft but I would suggest to wait for #198 to be resolved first

**Comment by greg0ire** [comment]
This is an issue, you can't convert it to draft (but you should be able to convert #193 to a draft)

**Comment by linawolf** [comment]
Arg that was what I wanted to do, got confused about where I was
