### ISSUE TITLE
Introduce contents (table of content) directive of rst

### ISSUE THREAD

**Issue by linawolf** [doctrine/rst-parser#202]
See https://docutils.sourceforge.io/docs/ref/rst/directives.html#table-of-contents

**Comment by greg0ire** [comment]
:thinking: sorry, what's the difference with `:toctree:` ? If this is something you use in Typo3, can you please link to an example? It should make it easier to understand.

**Comment by linawolf** [comment]
contents is making a a menu of the page you are currently on. (That is why it is RST Syntax, not Sphinx). It has settings like 
`:local:` where it only displays the subchapters of the chapter you are currently in.

We use it for example to make all chapters of the current page easaly accessible or to list all properties of an object or some such:
https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/ContentObjects/Content/Index.html

It also enables you to do what you are currently doing in the TocTreeBuilder Tests: Link from a current document to itself and only display one or two levels of headlines.

**Comment by greg0ire** [comment]
I guess it would benefit Doctrine for sure: https://github.com/doctrine/orm/blob/2.13.x/docs/en/reference/attributes-reference.rst … right now it looks like we are doing this kind of stuff manually :grimacing:

**Comment by wouterj** [comment]
I did use this directive in the Symfony docs once, but we've removed it when switching over to this RST parser. Would be cool if this project can have such directive, if it doesn't costs too much work to create it.

**Comment by linawolf** [comment]
I am working on something here, lets see how that works out

@greg0ire yeah, we used to do that too until someone ™️ got the idea that there is a directive for that
