### ISSUE TITLE
Intersphinx linking

### ISSUE THREAD

**Issue by linawolf** [doctrine/rst-parser#208]
TYPO3 docs heavily rely on intersphinx linking (https://docs.readthedocs.io/en/stable/guides/intersphinx.html / https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) We would also find it quite cool if doctrine and symfony would offer intersphinx links because then we could use them to link directly to sections without relying on file paths.

Should intersphinx linking be implemented as an additional package as is done in the phyton world?

**Comment by greg0ire** [comment]
I think Symfony does have links to Doctrine for instance in https://github.com/symfony/symfony-docs/blob/d85ca3e24b83111c16bcae6e0f18690502969015/doctrine.rst
The opposite is also true, for instance in https://www.doctrine-project.org/projects/doctrine-phpcr-odm/en/latest/reference/basic-mapping.html#symfony-bundle

Cc @weaverryan @wouterj

**Comment by linawolf** [comment]
The link from the symfony docs is not going to doctrine but to another page in symfony docs (from https://symfony.com/doc/current/doctrine.html) to (https://symfony.com/doc/current/doctrine/dbal.html) the link to the doctrine project is an external URL

The links from doctrine to symfony are also simple external links. These will neither adjust when the page is moved in the other documentation nor can I make automatic adjustments for versions etc, nor use the title.

In TYPO3 Third party extensions or specialized tutorials can use intersphinx linking. In our settings.cfg you can set shortcuts for all docs that you want to link to i.e:

```
t3coreapi      = https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/
t3tsref        = https://docs.typo3.org/m/typo3/reference-typoscript/11.5/en-us/
t3start        = https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/
```

I can then for example link to a tutorial:

```
Learn how to :ref:`Install TYPO3 with composer <t3start:composer>` (Tutorial Getting Started)!
```

If we release TYPO3 v12 LTS we can just switch the links to the newest version once and for all in the settings.cfg

**Comment by greg0ire** [comment]
The link form the Symfony doc is going (among other things) to https://www.doctrine-project.org/projects/doctrine-orm/en/current/reference/basic-mapping.html , so it is going to Doctrine (and is an external URL, yes). So it could be changed into an intersphinx link, right?

To clarify, I wasn't saying Doctrine or Symfony are already using intersphinx links, I was saying both might have use cases for it.

**Comment by wouterj** [comment]
If it's available, we can use this feature on symfony.com (we are rendering, and referencing, some [third-party bundle docs](https://symfony.com/bundles) on there) I think. But we don't have much issues with the current situation of hardcoding the references either.

**Comment by linawolf** [comment]
As we already used intersphinx linking heavily we cannot switch to the doctrine rst parser without intersphinx support. So for us it is a hard requriement

**Comment by linawolf** [comment]
So this extension for the doctrine/rst-parser can resolve intersphinx links: https://packagist.org/packages/t3docs/intersphinx#0.1.0

It interprets the `objects.inv.json` provided created by manuals that have been rendered with Python Sphinx.

The opposite direction -  creating a  `objects.inv.json` - is still missing.
