### ISSUE TITLE
Introduce Rector

### ISSUE THREAD

**Issue by linawolf** [doctrine/rst-parser#213]
To facilitate future PHP Updates etc. We could for example use it to introduce typed properties...

**Comment by greg0ire** [comment]
How exactly do you propose we use it? I'm currently using it to migrate `doctrine/orm` to  PHP 8 syntax, but I run it locally without committing the configuration or adding an extra dependency. Maybe you're proposing we using like Sonata does? https://github.com/sonata-project/SonataAdminBundle/blob/4.x/.github/workflows/qa.yaml#L70-L93

**Comment by linawolf** [comment]
In some TYPO3 projects we include rector and its configuration and have it run on cli and complain if not everything was applied:
https://github.com/TYPO3-Documentation/t3docs-examples/pull/151

If a false negative rule may not be applied we document this by adding it to the skip section:

https://github.com/TYPO3-Documentation/t3docs-examples/blob/main/rector.php#L32

**Comment by greg0ire** [comment]
Ok, do you want to give it a try on this repository? If it proves useful, we could promote it to `doctrine/.github` afterwards?
