### ISSUE TITLE
Titles should be targets

### ISSUE THREAD

**Issue by nikophil** [doctrine/rst-parser#47]
Hi,
referring to sphinx doc, titles should be targets as well
http://docutils.sourceforge.net/docs/user/rst/quickref.html#implicit-hyperlink-targets
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#implicit-hyperlink-targets

this now makes an error:
`Found invalid reference "title" in file "file"`

thanks :)

**Comment by jwage** [comment]
Does this work across documents or can you only reference a title in the same doc?

**Comment by weaverryan** [comment]
100%: you can only reference a title in the same doc. I just double-checked this.

**Comment by jwage** [comment]
I will fix this. This worked before I enhanced the errors for invalid references/links. It only worked because instead of erroring it just converted it to a link regardless of if the title existed or not. Now we can confirm the title exists and create the link.
