### ISSUE TITLE
Add missing admonitions

### ISSUE THREAD

**Issue by SenseException** [doctrine/rst-parser#6]
Not all documented specific admonitions are currently supported and should be added as described in the documentation: http://docutils.sourceforge.net/docs/ref/rst/directives.html#specific-admonitions

**Comment by jwage** [comment]
I have these implemented in doctrine/doctrine-website. They can probably be moved over to doctrine/rst-parser.

**Comment by linawolf** [comment]
They are also implemented in symfony-tools/docs-builder and now we also need them for TYPO3. so I think it would be really worthwhile to move them here. Can I do something to support this cause?

**Comment by linawolf** [comment]
Soo  according to https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html the admonitions to be supported would be:
attention, caution, danger, error, hint, important, note, tip, warning and the generic admonition. 

Both the doctrine website as the symphony docbilder well as TYPO3 docs also support seealso, so I would suggest to include it (https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Content/Admonitions.html)

The Symfony docs-builder has a best-practice directive which does not exist  neither in other projects nor sphinx but would be a cool feature that we could include.

For the tip admonition I copied the implementation of the doctrine website (#168) 

However I now noted that the doctrine website implementation renders the admonitions within the Admonition Directive, classes and icon names are set in the implementing subdirectives. 

The symfony docs-builder, however uses the template to style the output which is much cleaner: https://github.com/symfony-tools/docs-builder/blob/main/src/Directive/AbstractAdmonitionDirective.php

The single subdirective contains no more then names and titles: https://github.com/symfony-tools/docs-builder/blob/main/src/Directive/TipDirective.php

Therefore I would vote that we use the symfony way of implementing Admonitions (before we integrate all of them) as they are easier to style also when the TYPO3 Docs Team will adopt the doctrine rst-parser

**Comment by linawolf** [comment]
@SenseException can this be closed?
