### ISSUE TITLE
Include the file (and if possible line number) where an error occurs

### ISSUE THREAD

**Issue by weaverryan** [doctrine/rst-parser#71]
I know this could be tricky, at least the "line number" part. If you, for example, type a directive `.. foo::`, you will just get:

> Unknown directive: role  

I suppose we could store some "current context" somewhere so we can include it when the ErrorManager throws the errors?

**Comment by wouterj** [comment]
@weaverryan didn't you fix this in your latest PR?

**Comment by linawolf** [comment]
This was fixed by #73
