### ISSUE TITLE
missing support for many inline markup items - like :kbd:

### ISSUE THREAD

**Issue by weaverryan** [doctrine/rst-parser#78]
We know about `:ref:`and `:doc:`, but there are actually a bunch of other `:something:` inline syntaxes supported by Sphinx - http://www.sphinx-doc.org/es/stable/markup/inline.html#cross-referencing-documents

We use at least one in the symfony docs - `:kbd:`. I don't think that we should go and implement *every* one of these (there are a lot) - but it looks like we *do* need some systematic way of handling this `:something:` syntax. If I'm not mistaken, it looks like we currently treat *anything* matching `:*:` as a reference: https://github.com/doctrine/rst-parser/blob/8e8aa20eb072e69f557e4a49c4db0b50928a4ef6/lib/Span/SpanProcessor.php#L107

**Comment by weaverryan** [comment]
Closing because I'm an idiot! I know reference are already an extensible system - I don't know why I completely forgot about this temporarily :)

**Comment by weaverryan** [comment]
Oooop, nevermind.

The reference system DOES exist for entirely this syntax, but it assumes that you always want an `a` tag (a "reference"). However, for the example of `:kbd:`, we actually want a `<code>` tag (or a `<kbd>` tag to be more hipster).

**Comment by wouterj** [comment]
This ```:something:`..` ``` syntax (called role marker) is actually an extension of the `` `...` `` "interpreted text" feature in reStructuredText: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#interpreted-text

> The "role" of the interpreted text determines how the text is interpreted. The role may be inferred implicitly (as above; the "default role" is used) or indicated explicitly, using a role marker. [...] Interpreted text allows extensions to the available inline descriptive markup constructs

So, while it's used for references in `:doc:` and `:ref:`, it's not at all limited to that.

**Comment by linawolf** [comment]
@weaverryan did this feature request get resolved by https://github.com/doctrine/rst-parser/pull/214?

**Comment by weaverryan** [comment]
I'm not positive - and I don't have a quick way to check right now, but I think that PR would do it. Thanks :)

**Comment by linawolf** [comment]
@weaverryan if it is not sufficient I would be greatful if you could provide a failed test
