### ISSUE TITLE
PreNodeRenderEvent to have access to the current rendering file 

### ISSUE THREAD

**Issue by nikophil** [doctrine/rst-parser#84]
Hi,

we would like to perform some quality control checks when the parser is rendering a code block with some php code.
First of all, we want to perform a `php-cs-fixer` check after every `CodeNode` rendering.
It could be done thanks to `PostNodeRenderEvent`:

```php
    public function postNodeRender(PostNodeRenderEvent $postNodeRenderEvent)
    {
        $node = $postNodeRenderEvent->getRenderedNode()->getNode();
        if (!$node instanceof CodeNode) {
            return;
        }

        // perform some checks...
    }
```

the problem is we don't have access here to the current environment, or current file being rendered.
I don't even know if it's possible here to have this information, but that would be really appreciated, otherwise, we couldn't inform the user where the problem is located.

What do you think ?
thanks for your help on that.

**Comment by jwage** [comment]
The Environment object is intended to be 1 instance per file. It has everything about that file being parsed.
