### ISSUE TITLE
Add some cache behavior

### ISSUE THREAD

**Issue by nikophil** [doctrine/rst-parser#85]
Hi,

Sphinx provide some cache behavior and we're wondering if it would be possible to have such feature...
We were thinking that we could save the meta between builds and automatically re-use the meta for each file, unless it detects if the source rst file has been updated. And then re-render only files that _need_ to be rendered.

This is important on symfony.com because there are a LOT of versions of the docs & bundles to render. But, we also want to update the docs fairly quickly after a pull request is merged. To do that, currently, once per day, the docs are "fully" rebuild (using the -a -E options). But much more frequently (every 20 minutes?), a CRON job just does the "partial" build.

what do you think about that ?

thanks.

**Comment by jwage** [comment]
Yes, it is possible and the old https://github.com/Gregwar/RST packaged we forked from has this functionality so it could be re-implemented.

**Comment by weaverryan** [comment]
Is it just a matter of caching the "metas" and being smart enough to only rebuild the metas for files that have a new last modified time? Or is there something that the previous library did also during the rendering process - i.e. to only re-render the HTML files that have "changed"?

**Comment by jwage** [comment]
It used to dump the metadata to a file and then it'd read that file when building. It'd only parse the file if the last modified time had changed or it was a new file that had never been built.

**Comment by javiereguiluz** [comment]
I guess this one can be closed. A long time ago this project introduced a cache mechanism based on the modified time of each item (see https://github.com/doctrine/rst-parser/pull/112).
